### ISSUE TITLE
def _compute_domain changed in odoo base

### ISSUE THREAD

**Issue by kikosanchez** [itpp-labs/access-addons#129]
Hi

        OCB/odoo/addons/base/ir/ir_rule.py
      
changed in return from _compute_domain, 

could you please add this modification ...

Thanks
REgards

**Comment by yelizariev** [comment]
I do not quite understand you. First, which module should be fixed and which version? What exactly doesn't work due to the change in odoo source?

**Comment by kikosanchez** [comment]
Hi
Sorry for my bad english ...

Odoo base code has change the return in _compute_domain because a change in expression.AND function. [https://github.com/OCA/OCB/blob/11.0/odoo/addons/base/ir/ir_rule.py](url)

Look at lines 99-100. 

This is the commit:
[https://github.com/OCA/OCB/commit/023dfaeb6b9499943315358edaa01c8f823ee695](url) 

I'm not sure the about the reason, but it doesn't work in some cases.

**Comment by trojikman** [comment]
I think the described case does not apply to this repository. Feel free to reopen issue with more details
